version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ../backend/src/main/docker
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
       DB_HOST: db
       DB_PORT: 5432
       DB_NAME: ${DB_NAME}
       DB_USERNAME: ${DB_USERNAME}
       DB_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "8080:8080"
    networks:
      - my-shared-network

  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5000:5432"
    networks:
      - my-shared-network

  frontend:
    image: frontend
    build:
      context: ../frontend
    container_name: frontend
    restart: always
    environment:
      BE_HOST: backend
      BE_PORT: 8080
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my-shared-network

#  nginx:
#    build:
#      context: ../nginx
#    container_name: nginx
#    restart: always
#    ports:
#      - "8000:8000"
#    networks:
#      - my-shared-network
#    depends_on:
#      - backend
#      - frontend

networks:
  my-shared-network: {}
